steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/health-monitoring-backend', './backend']
    
  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/health-monitoring-frontend', './frontend']
    
  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/health-monitoring-backend']
    
  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/health-monitoring-frontend']
    
  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'health-monitoring-backend',
      '--image', 'gcr.io/$PROJECT_ID/health-monitoring-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--set-env-vars', 'GOOGLE_GENAI_USE_VERTEXAI=FALSE,GOOGLE_API_KEY=AIzaSyBk9WYIPXXR5dTEHHaOHTiZH2sDqJQDNlI'
    ]
    
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'health-monitoring-frontend',
      '--image', 'gcr.io/$PROJECT_ID/health-monitoring-frontend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '80',
      '--memory', '512Mi',
      '--cpu', '1'
    ]

images:
  - 'gcr.io/$PROJECT_ID/health-monitoring-backend'
  - 'gcr.io/$PROJECT_ID/health-monitoring-frontend'